export const SERVICES = [
  { id: 'digital-growth',      title: 'Digital Growth',                     count: 7, img: '/categories/digital-growth.svg',      hoverImg: '/categories/digital-growth.svg',              icon: '/icons/brand-building.svg',
    cardSubs: ['SEO / AEO / GEO', 'Paid Search & AI Ads', 'Website Design', 'Email Marketing'],
    subs: ['SEO / AEO / GEO', 'Paid Search & AI Ads', 'Website Design', 'Email Marketing', 'Data-Driven Direct Mail', 'Digital PR', 'Conversion Strategy'] },
  { id: 'programmatic',        title: 'Programmatic',                       count: 7, img: '/categories/programmatic.webp',       hoverImg: '/services/svc-programmatic-rollover.webp',    icon: '/icons/programmatic.svg',
    cardSubs: ['Remarketing', 'Full-Funnel', 'Display', 'CTV / OTT'],
    subs: ['Remarketing', 'Full-Funnel', 'Display', 'Audio', 'CTV / OTT', 'In-Game', 'Pre-Roll Video'] },
  { id: 'technology',          title: 'Technology Strategy & Engineering',  count: 7, img: '/categories/technology.webp',         hoverImg: '/services/svc-tech-rollover.webp',            icon: '/icons/tech.svg',
    cardSubs: ['Technology Audits', 'CRM & Automation', 'Custom Software', 'Reporting & Analytics'],
    subs: ['Technology Audits', 'CRM & Automation', 'Systems Integration', 'Custom Software', 'WordPress Engineering', 'Reporting & Analytics', 'AI Applications'] },
  { id: 'social',              title: 'Social Media',                       count: 7, img: '/categories/social.webp',             hoverImg: '/services/svc-social-rollover.webp',          icon: '/icons/social.svg',
    cardSubs: ['Social Strategy', 'Content Creation', 'Paid Social', 'Influencer & Creator Marketing'],
    subs: ['Social Strategy', 'Content Creation', 'Social Management', 'Paid Social', 'Influencer & Creator Marketing', 'Community Management', 'Social Analytics'] },
  { id: 'fraud',               title: 'Fraud Prevention',                   count: 7, img: '/categories/fraud.webp',              hoverImg: '/services/svc-fraud-rollover.webp',           icon: '/icons/fraud.svg',
    cardSubs: ['Ad Fraud Detection', 'Click Fraud', 'Lead & Form Fraud', 'Brand Safety'],
    subs: ['Ad Fraud Detection', 'Click Fraud', 'Bot & Invalid Traffic', 'Lead & Form Fraud', 'Brand Safety', 'Ad Verification', 'Traffic Auditing'] },
  { id: 'privacy-compliance',  title: 'Privacy & Compliance',               count: 7, img: '/categories/privacy-compliance.svg',  hoverImg: '/categories/privacy-compliance.svg',          icon: '/icons/trad-full-service.svg',
    cardSubs: ['Data Mapping', 'Consent Management', 'Consumer Privacy Requests', 'Privacy Audits'],
    subs: ['Data Mapping', 'Consent Management', 'Cookie Compliance', 'Consumer Privacy Requests', 'Tracking Governance', 'Privacy Audits', 'Vendor Compliance'] },
  { id: 'branding',            title: 'Branding',                           count: 7, img: '/categories/brand-creation.webp',     hoverImg: '/services/svc-brand-creation-rollover.webp',  icon: '/icons/brand-creation.svg',
    cardSubs: ['Logo Design', 'Corporate Identity', 'Brand Guidelines', 'Business Collateral'],
    subs: ['Logo Design', 'Corporate Identity', 'Brand Guidelines', 'Business Collateral', 'Vehicle & Fleet Wraps', 'Packaging & POP', 'Uniforms & Apparel'] },
  { id: 'authority-influence', title: 'Authority & Influence',              count: 7, img: '/categories/authority-influence.svg', hoverImg: '/categories/authority-influence.svg',         icon: '/icons/brand-specialties.svg',
    cardSubs: ['Personal Branding', 'Public Relations', 'Podcast Management', 'Author Services'],
    subs: ['Personal Branding', 'Public Relations', 'Podcast Management', 'Media Pitching', 'Event Management', 'Author Services', 'Thought Leadership'] },
]

/* Mega-menu order. The panel is a 2-column grid that fills row-wise, so this
   array interleaves the two dropdown columns (left, right, left, right...). */
export const MEGA_SERVICES = [
  { id: 'digital-growth',      title: 'Digital Growth',                    count: 7, img: '/categories/digital-growth-menu.svg',      icon: '/icons/brand-building.svg' },
  { id: 'programmatic',        title: 'Programmatic',                      count: 7, img: '/services/svc-programmatic-rollover.webp',     icon: '/icons/programmatic.svg' },
  { id: 'technology',          title: 'Technology Strategy & Engineering', count: 7, img: '/services/svc-tech-rollover.webp',             icon: '/icons/tech.svg' },
  { id: 'social',              title: 'Social Media',                      count: 7, img: '/services/svc-social-rollover.webp',           icon: '/icons/social.svg' },
  { id: 'fraud',               title: 'Fraud Prevention',                  count: 7, img: '/services/svc-fraud-rollover.webp',            icon: '/icons/fraud.svg' },
  { id: 'privacy-compliance',  title: 'Privacy & Compliance',              count: 7, img: '/categories/privacy-compliance-menu.svg',  icon: '/icons/trad-full-service.svg' },
  { id: 'branding',            title: 'Branding',                          count: 7, img: '/services/svc-brand-creation-rollover.webp',   icon: '/icons/brand-creation.svg' },
  { id: 'authority-influence', title: 'Authority & Influence',             count: 7, img: '/categories/authority-influence-menu.svg', icon: '/icons/brand-specialties.svg' },
]

/* Rich, per-service detail content. Only services present here render the
   expanded alternating-feature layout; others fall back to the generic body. */
export const SERVICE_DETAILS = {
  'digital-growth': {
    cta: { title: 'Ready to turn attention into growth?' },
    hero: {
      eyebrow: 'Digital Growth',
      title: 'Digital Growth',
      lead: 'Being online is not enough. We build connected acquisition strategies that help brands get found, capture demand and turn attention into measurable business growth.',
      bg: '/services/brand-building/hero.webp',
    },
    intro: {
      title: 'Get found. Get chosen. Grow.',
      copy: 'Search, advertising, websites, email and data all influence the customer journey. We connect them into measurable strategies built around leads, customers and revenue.',
      stats: [
        { value: 'DISCOVER', label: 'Search & AI visibility' },
        { value: 'ATTRACT', label: 'High-intent traffic' },
        { value: 'CONVERT', label: 'Better experiences' },
        { value: 'REENGAGE', label: 'Turn data into growth' },
      ],
    },
    features: [
      { id: 'seo-aeo-geo', kicker: '01', title: 'SEO / AEO / GEO', image: '/services/programmatic/seo.svg',
        copy: 'Be found wherever people search — from Google to AI-powered answer and generative engines.',
        points: ['Technical & on-page SEO', 'Answer Engine Optimization', 'Generative Engine Optimization'] },
      { id: 'paid-search', kicker: '02', title: 'Paid Search & AI Ads', image: '/services/programmatic/sem.svg',
        copy: 'Capture high-intent demand through Google Ads, Microsoft Advertising, AI advertising platforms and performance-driven paid acquisition.',
        points: ['Google Ads', 'Microsoft Advertising', 'OpenAI / AI advertising', 'Conversion tracking & optimization'] },
      { id: 'website-design', kicker: '03', title: 'Website Design', image: '/services/digital-growth/website.svg',
        copy: 'Design high-performing websites that combine brand, user experience, search visibility and conversion strategy.',
        points: ['Website strategy & UX', 'Custom design', 'Landing pages', 'SEO-ready architecture'] },
      { id: 'email-marketing', kicker: '04', title: 'Email Marketing', image: '/services/digital-growth/email.svg',
        copy: 'Turn customer and prospect data into automated, personalized communication.',
        points: ['Campaign strategy', 'Lead nurture', 'Segmentation', 'Customer lifecycle marketing'] },
      { id: 'direct-mail', kicker: '05', title: 'Data-Driven Direct Mail', image: '/services/trad/directmail.svg',
        copy: 'Combine audience data and variable printing to make physical mail as targeted as digital advertising.',
        points: ['Audience targeting', 'Variable data printing', 'Personalized creative', 'CRM/customer list campaigns'] },
      { id: 'digital-pr', kicker: '06', title: 'Digital PR', image: '/services/trad/pr.svg',
        copy: 'Use corporate news, press distribution and earned digital visibility to build authority and search presence.',
        points: ['Press releases', 'Corporate announcements', 'Media outreach', 'Digital amplification'] },
      { id: 'conversion-strategy', kicker: '07', title: 'Conversion Strategy', image: '/services/digital-growth/conversion.svg',
        copy: 'Improve what happens after the visitor arrives.',
        points: ['Conversion optimization', 'Landing page strategy', 'Lead funnels', 'Customer journey analysis'] },
    ],
    note: {
      title: 'And yes, we still do traditional media.',
      copy: 'When traditional channels make strategic sense, we can plan and execute television, radio, print, outdoor and other offline media. These are supporting capabilities — not a separate Covert service category.',
    },
  },

  programmatic: {
    cta: { title: 'Reach the right audience, wherever they are.' },
    hero: {
      eyebrow: 'Programmatic Media',
      title: 'Programmatic',
      lead: 'Data-driven media that finds the right audience at the right moment across every screen — planned, bought and continuously optimized using real-time data.',
      bg: '/services/programmatic/hero.webp',
    },
    intro: {
      title: 'Precision at scale.',
      copy: 'Use audience intelligence, behavioral data and automation to reach customers wherever they consume media.',
      stats: [
        { value: 'TARGET' },
        { value: 'REACH' },
        { value: 'OPTIMIZE' },
        { value: 'SCALE' },
      ],
    },
    features: [
      { id: 'remarketing', kicker: '01', title: 'Remarketing', image: '/services/programmatic/remarketing.svg',
        copy: 'Re-engage people who have already interacted with the brand and move them toward the next action.' },
      { id: 'full-funnel', kicker: '02', title: 'Full-Funnel Media', image: '/services/programmatic/full-funnel.svg',
        copy: 'Build coordinated programmatic media from awareness through conversion and re-engagement.' },
      { id: 'display', kicker: '03', title: 'Display Advertising', image: '/services/programmatic/display.svg',
        copy: 'Reach targeted audiences across premium websites and digital environments with measurable display campaigns.' },
      { id: 'audio', kicker: '04', title: 'Programmatic Audio', image: '/services/programmatic/audio.svg',
        copy: 'Reach audiences through streaming audio, podcasts and digital radio environments.' },
      { id: 'ctv-ott', kicker: '05', title: 'CTV / OTT', image: '/services/programmatic/ctv.svg',
        copy: 'Reach viewers on connected televisions and streaming platforms with audience-driven video advertising.' },
      { id: 'in-game', kicker: '06', title: 'In-Game Advertising', image: '/services/programmatic/in-game.svg',
        copy: 'Place brand messages inside gaming environments where appropriate to the audience and campaign.' },
      { id: 'pre-roll', kicker: '07', title: 'Pre-Roll Video', image: '/services/programmatic/pre-roll.svg',
        copy: 'Deliver targeted video advertising before or within digital video content across relevant inventory.' },
    ],
  },

  technology: {
    cta: { title: 'Your technology should be an advantage.' },
    hero: {
      eyebrow: 'Technology Strategy & Engineering',
      title: 'Technology',
      lead: 'Technology should simplify your business, not complicate it. We audit, optimize, integrate and build the systems behind modern organizations — from enterprise CRM and reporting infrastructure to proprietary software and custom applications.',
      bg: '/services/technology/hero.webp',
    },
    intro: {
      title: 'Better technology. Less waste.',
      copy: 'Most companies do not need more software — they need the technology they already have to work better.',
      stats: [
        { value: 'AUDIT' },
        { value: 'OPTIMIZE' },
        { value: 'INTEGRATE' },
        { value: 'BUILD' },
      ],
    },
    features: [
      { id: 'audits', kicker: '01', title: 'Technology Audits', image: '/services/technology/strategy.svg',
        copy: 'Evaluate the entire technology stack to identify unnecessary costs, redundant systems, inefficiencies and opportunities to simplify.',
        points: ['Technology stack evaluation', 'Cost, redundancy & utilization analysis', 'Strategic technology roadmap'] },
      { id: 'crm-automation', kicker: '02', title: 'CRM & Automation', image: '/services/technology/crm.svg',
        copy: 'Implement, migrate, customize and optimize CRM platforms around the way the organization actually works.',
        points: ['CRM setup, migration & customization', 'Pipelines, workflows & lead routing', 'Salesforce, HubSpot, Zoho, GoHighLevel, Coperniq & more'] },
      { id: 'systems-integration', kicker: '03', title: 'Systems Integration', image: '/services/technology/integration.svg',
        copy: 'Connect disconnected systems so data can move automatically across marketing, sales and operations.',
        points: ['API & platform integrations', 'Data synchronization & workflow automation', 'Marketing, sales & operational integrations'] },
      { id: 'custom-software', kicker: '04', title: 'Custom Software', image: '/services/technology/app.svg',
        copy: 'Design and build proprietary applications, internal tools and customer-facing platforms for complex business requirements.',
        points: ['Custom applications & platforms', 'Internal tools, portals & calculators', 'APIs, databases & proprietary software'] },
      { id: 'wordpress', kicker: '05', title: 'WordPress Engineering', image: '/services/technology/web.svg',
        copy: 'Go beyond standard website builds with custom WordPress functionality and technical infrastructure.',
        points: ['Custom WordPress plugins', 'APIs & third-party integrations', 'Advanced functionality & workflows'] },
      { id: 'reporting', kicker: '06', title: 'Reporting & Analytics', image: '/services/technology/reporting.svg',
        copy: 'Connect data across advertising, websites, CRM and sales systems to create decision-ready reporting.',
        points: ['Executive dashboards & custom reporting', 'Marketing attribution & lead-to-revenue tracking', 'Cross-platform data integration'] },
      { id: 'ai-applications', kicker: '07', title: 'AI Applications', image: '/services/technology/ai.svg',
        copy: 'Design practical AI-powered applications and automated workflows around real business needs.',
        points: ['Custom AI applications', 'Intelligent workflow automation', 'AI integrations & business tools'] },
    ],
  },

  social: {
    cta: { title: 'Make your brand worth following.' },
    hero: {
      eyebrow: 'Social Media',
      title: 'Social Media',
      lead: 'Social media is not about posting more. It is about creating the right content, reaching the right audience and building a brand people choose to follow, engage with and remember.',
      bg: '/services/social/hero.webp',
    },
    intro: {
      title: 'Attention is earned.',
      copy: 'We manage the entire social ecosystem — from strategy and creative to distribution, engagement and measurement.',
      stats: [
        { value: 'STRATEGIZE' },
        { value: 'CREATE' },
        { value: 'AMPLIFY' },
        { value: 'MEASURE' },
      ],
    },
    features: [
      { id: 'strategy', kicker: '01', title: 'Social Strategy', image: '/services/social/strategy.svg',
        copy: 'Define the audience, platform role, content pillars and growth strategy before execution begins.',
        points: ['Platform & audience strategy', 'Content pillars & editorial planning', 'Campaign and growth strategy'] },
      { id: 'content', kicker: '02', title: 'Content Creation', image: '/services/social/content.svg',
        copy: 'Create content built for the platforms where people consume it.',
        points: ['Reels & short-form video', 'Graphics, photography & animation', 'Copywriting & branded content'] },
      { id: 'management', kicker: '03', title: 'Social Management', image: '/services/social/management.svg',
        copy: 'Manage the day-to-day execution of active social channels.',
        points: ['Content calendars & scheduling', 'Cross-platform publishing', 'Ongoing channel optimization'] },
      { id: 'paid', kicker: '04', title: 'Paid Social', image: '/services/social/paid.svg',
        copy: 'Combine creative and media strategy to reach, retarget and convert social audiences.',
        points: ['Paid social campaign strategy', 'Audience targeting & remarketing', 'Creative testing & optimization'] },
      { id: 'influencer', kicker: '05', title: 'Influencer & Creator Marketing', image: '/services/social/influencer.svg',
        copy: 'Identify, vet and manage creator partnerships based on relevance and fit.',
        points: ['Influencer identification & vetting', 'Outreach, negotiation & campaign management', 'Creator content & paid amplification'] },
      { id: 'community', kicker: '06', title: 'Community Management', image: '/services/social/community.svg',
        copy: 'Manage conversations and engagement around the brand.',
        points: ['Comment & message engagement', 'Audience interaction', 'Reputation & escalation support'] },
      { id: 'analytics', kicker: '07', title: 'Social Analytics', image: '/services/social/analytics.svg',
        copy: 'Analyze content, audiences, campaigns and conversion behavior to continuously improve strategy.',
        points: ['Content & audience performance', 'Campaign reporting', 'Growth, engagement & conversion analysis'] },
    ],
  },

  fraud: {
    cta: { title: 'Protect every dollar behind your marketing.' },
    hero: {
      eyebrow: 'Fraud Prevention',
      title: 'Fraud Prevention',
      lead: 'Protect every dollar of media spend and every lead entering your funnel. We detect invalid traffic, bots, click fraud and unsafe placements before they distort performance.',
      bg: '/services/fraud/hero.webp',
    },
    intro: {
      title: 'Protect the spend. Protect the signal.',
      copy: 'Fraud does not just waste money — it corrupts the data businesses use to make decisions.',
      stats: [
        { value: 'DETECT' },
        { value: 'BLOCK' },
        { value: 'VERIFY' },
        { value: 'PROTECT' },
      ],
    },
    features: [
      { id: 'ad-fraud', kicker: '01', title: 'Ad Fraud Detection', image: '/services/fraud/addetection.svg',
        copy: 'Identify and filter fraudulent ad activity before it distorts performance and wastes budget.',
        points: ['Invalid traffic detection', 'Pre-bid / post-bid controls', 'Spend recovery insight'] },
      { id: 'click-fraud', kicker: '02', title: 'Click Fraud', image: '/services/fraud/clickfraud.svg',
        copy: 'Detect suspicious and fraudulent clicks that artificially inflate paid media costs.',
        points: ['Anomaly detection', 'IP/device blocking', 'Automated fraud rules'] },
      { id: 'bot-traffic', kicker: '03', title: 'Bot & Invalid Traffic', image: '/services/fraud/bot.svg',
        copy: 'Identify automated and invalid traffic that contaminates website, campaign and analytics data.',
        points: ['Bot detection', 'Invalid traffic filtering', 'Traffic quality monitoring'] },
      { id: 'lead-fraud', kicker: '04', title: 'Lead & Form Fraud', image: '/services/fraud/leadfraud.svg',
        copy: 'Reduce fake leads, spam and automated form submissions before they reach sales teams.',
        points: ['Form fraud detection', 'Spam and bot filtering', 'Lead-quality controls'] },
      { id: 'brand-safety', kicker: '05', title: 'Brand Safety', image: '/services/fraud/brandsafety.svg',
        copy: 'Keep ads away from content and environments that do not align with the brand.',
        points: ['Contextual controls', 'Inventory allow/block logic', 'Reputation protection'] },
      { id: 'ad-verification', kicker: '06', title: 'Ad Verification', image: '/services/fraud/verification.svg',
        copy: 'Verify that advertising appears where intended and meets campaign quality requirements.',
        points: ['Placement verification', 'Viewability / quality checks', 'Delivery validation'] },
      { id: 'traffic-auditing', kicker: '07', title: 'Traffic Auditing', image: '/services/fraud/audit.svg',
        copy: 'Review traffic sources and quality to identify waste, anomalies and hidden performance problems.',
        points: ['Source quality review', 'Anomaly analysis', 'Optimization recommendations'] },
    ],
  },

  'privacy-compliance': {
    cta: { title: 'Build privacy into the way your business works.' },
    hero: {
      eyebrow: 'Privacy & Compliance',
      title: 'Privacy & Compliance',
      lead: 'Know what data you are collecting, where it is going and whether you have permission to use it. We help organizations build privacy into the technology and marketing systems behind their business.',
      bg: '/services/privacy-compliance/hero.svg',
    },
    intro: {
      title: 'Privacy built into the system.',
      copy: 'Privacy is more than a banner. We help businesses understand their data ecosystem and operationalize consent, requests and governance across their technology.',
      stats: [
        { value: 'MAP' },
        { value: 'CONSENT' },
        { value: 'GOVERN' },
        { value: 'RESPOND' },
      ],
    },
    features: [
      { id: 'data-mapping', kicker: '01', title: 'Data Mapping', image: '/services/privacy-compliance/mapping.svg',
        copy: 'Identify the technologies, trackers, forms, platforms and destinations involved in the collection and movement of customer data.',
        points: ['Website and app data flows', 'Tracking and platform inventory', 'Data destination documentation'] },
      { id: 'consent', kicker: '02', title: 'Consent Management', image: '/services/privacy-compliance/consent.svg',
        copy: 'Implement and optimize consent systems so tracking technologies respond to user choices appropriately.',
        points: ['Consent platform implementation', 'Universal consent consulting', 'Category and signal configuration'] },
      { id: 'cookies', kicker: '03', title: 'Cookie Compliance', image: '/services/privacy-compliance/cookies.svg',
        copy: 'Review and classify cookies and tracking technologies and align deployment with consent requirements.',
        points: ['Cookie and script review', 'Classification and governance', 'Consent-aware deployment'] },
      { id: 'requests', kicker: '04', title: 'Consumer Privacy Requests', image: '/services/privacy-compliance/requests.svg',
        copy: 'Build workflows for access, deletion, correction and opt-out requests, including SRR / DSAR processes.',
        points: ['Request intake and routing', 'SRR / DSAR workflows', 'Internal process documentation'] },
      { id: 'tracking-governance', kicker: '05', title: 'Tracking Governance', image: '/services/privacy-compliance/governance.svg',
        copy: 'Make sure analytics, advertising pixels and other technologies respect the correct consent state.',
        points: ['Tag firing rules', 'Consent signal validation', 'Analytics / ad platform governance'] },
      { id: 'audits', kicker: '06', title: 'Privacy Audits', image: '/services/privacy-compliance/audits.svg',
        copy: 'Review the digital ecosystem for privacy-process and tracking-control gaps.',
        points: ['Technology and tracker review', 'Consent implementation review', 'Operational recommendations'] },
      { id: 'vendors', kicker: '07', title: 'Vendor Compliance', image: '/services/privacy-compliance/vendors.svg',
        copy: 'Review third-party technology and vendor data practices as part of the broader data ecosystem.',
        points: ['Vendor inventory', 'Data-sharing review', 'Governance recommendations'] },
    ],
    note: {
      title: 'Technical and operational, not legal.',
      copy: 'This is technical and operational privacy consulting — we build and govern the systems behind your data. It is not legal advice, and it does not replace your counsel.',
    },
  },

  branding: {
    cta: { title: 'Build a brand people remember.' },
    hero: {
      eyebrow: 'Branding',
      title: 'Branding',
      lead: 'Build a brand people recognize before they read the name. From identity systems to fleet graphics, collateral and physical brand applications, we create brands built to work everywhere.',
      bg: '/services/brand-creation/hero.webp',
    },
    intro: {
      title: 'One brand. Everywhere it shows up.',
      copy: 'A strong identity needs to work consistently from a business card and website to a truck, uniform, package or retail display.',
      stats: [
        { value: 'DEFINE' },
        { value: 'DESIGN' },
        { value: 'APPLY' },
        { value: 'STANDARDIZE' },
      ],
    },
    features: [
      { id: 'logo-design', kicker: '01', title: 'Logo Design', image: '/services/brand-creation/logo.svg',
        copy: 'Create a distinctive brand mark and flexible logo system that works across physical and digital environments.',
        points: ['Primary and secondary marks', 'Lockups & variations', 'Responsive / scalable logo system'] },
      { id: 'corporate-identity', kicker: '02', title: 'Corporate Identity', image: '/services/brand-creation/identity.svg',
        copy: 'Build the complete visual identity system around the logo.',
        points: ['Color & type systems', 'Corporate identity assets', 'Core visual language'] },
      { id: 'brand-guidelines', kicker: '03', title: 'Brand Guidelines', image: '/services/brand-creation/guidelines.svg',
        copy: 'Document the standards that keep the brand consistent as it grows.',
        points: ['Usage standards', 'Asset libraries', 'Consistency at scale'] },
      { id: 'collateral', kicker: '04', title: 'Business Collateral', image: '/services/branding/collateral.svg',
        copy: 'Apply the identity to the everyday materials used by sales and operations.',
        points: ['Business cards', 'Brochures & sales sheets', 'Folders, presentations & leave-behinds'] },
      { id: 'fleet-wraps', kicker: '05', title: 'Vehicle & Fleet Wraps', image: '/services/branding/fleet.svg',
        copy: 'Extend the brand to vehicles and fleets with clear, recognizable visual applications.',
        points: ['Fleet graphic design', 'Vehicle wrap systems', 'Production-ready artwork'] },
      { id: 'packaging-pop', kicker: '06', title: 'Packaging, POP & Displays', image: '/services/brand-specialties/packaging.svg',
        copy: 'Create packaging and point-of-purchase materials that carry the brand into physical environments.',
        points: ['Packaging design', 'POP materials', 'Retail / display graphics'] },
      { id: 'apparel', kicker: '07', title: 'Uniforms & Apparel', image: '/services/branding/apparel.svg',
        copy: 'Translate the identity into employee apparel and branded uniforms.',
        points: ['Uniform systems', 'Branded apparel', 'Production-ready applications'] },
    ],
  },

  'authority-influence': {
    cta: { title: 'Turn expertise into authority.' },
    hero: {
      eyebrow: 'Authority & Influence',
      title: 'Authority & Influence',
      lead: 'Turn expertise into visibility, credibility and influence. We build the people behind the brand through public relations, podcasts, media, events, publishing and thought leadership.',
      bg: '/services/authority-influence/hero.svg',
    },
    intro: {
      title: 'Build the name behind the brand.',
      copy: 'Great companies benefit when the people leading them become trusted, recognizable voices in their industries.',
      stats: [
        { value: 'POSITION' },
        { value: 'PUBLISH' },
        { value: 'PITCH' },
        { value: 'AMPLIFY' },
      ],
    },
    features: [
      { id: 'personal-branding', kicker: '01', title: 'Personal Branding', image: '/services/brand-building/positioning.svg',
        copy: 'Shape the positioning, message and presence of founders, executives, authors and experts.',
        points: ['Personal positioning', 'Messaging & visual presence', 'Reputation and visibility strategy'] },
      { id: 'public-relations', kicker: '02', title: 'Public Relations', image: '/services/authority-influence/pr.svg',
        copy: 'Build visibility and credibility for executives, founders, experts and individuals through earned-media strategy.',
        points: ['PR strategy', 'Story development', 'Earned media outreach'] },
      { id: 'podcast-management', kicker: '03', title: 'Podcast Management', image: '/services/authority-influence/podcast.svg',
        copy: 'Develop, produce, manage and promote podcasts as an authority-building platform.',
        points: ['Podcast development & production', 'Guest management & distribution', 'Promotion & growth'] },
      { id: 'media-pitching', kicker: '04', title: 'Media Pitching', image: '/services/authority-influence/pitching.svg',
        copy: 'Pitch experts and leaders to relevant publications, podcasts and media opportunities.',
        points: ['Story angles', 'Media / podcast outreach', 'Interview and opportunity coordination'] },
      { id: 'event-management', kicker: '05', title: 'Event Management', image: '/services/authority-influence/events.svg',
        copy: 'Plan and support speaking events, launches, branded experiences and related promotional opportunities.',
        points: ['Speaking events', 'Launches & activations', 'Sponsorship opportunities'] },
      { id: 'author-services', kicker: '06', title: 'Author Services', image: '/services/authority-influence/author.svg',
        copy: 'Support authors through publishing, launch and ongoing promotion.',
        points: ['Publishing support', 'Book launches', 'Book marketing & promotional strategy'] },
      { id: 'thought-leadership', kicker: '07', title: 'Thought Leadership', image: '/services/authority-influence/thought.svg',
        copy: 'Turn expertise into a consistent, recognizable point of view across content and media.',
        points: ['Executive content strategy', 'Articles & contributed content', 'Speaking and visibility strategy'] },
    ],
  },

}

export const MEGA_ABOUT = [
  { id: 'covertcom',  label: 'Covert Communication', icon: '/icons/about/about-covertcom.svg',    img: '/about/about-covertcom-rollover.webp',   cardBg: '/about/about-covertcom-rollover.webp', href: '/about/covertcom',
    heroImg: '/about/about-covertcom-emblem.webp', heroBg: '/about/about-hero-texture.webp', heroEmblem: '/about/about-hero-emblem.webp', tagline: 'The full-service agency behind the brand.' },
  { id: 'anna',       label: 'Anna Covert',           icon: '/icons/about/about-anna.png',  img: '/about/about-anna-rollover.webp',        cardBg: '/about/card-anna.webp', href: '/about/anna',
    heroImg: '/about/about-anna-emblem.webp', heroBg: '/about/about-hero-texture.webp', heroEmblem: '/about/about-anna-hero-emblem.webp', heroEmblemSharp: true, figure: '/about/about-anna-figure.webp', photo: '/about/about-anna-photo.webp', tagline: 'Founder, author, and the voice behind Covert Communication.' },
  { id: 'covertteam',label: 'The Covert Team',        icon: '/icons/about/about-covertteam.svg',           img: '/about/about-covertteam-rollover.webp',  cardBg: '/about/card-covertteam.webp', href: '/about/covertteam',
    heroBg: '/about/about-hero-texture.webp', heroEmblem: '/about/about-hero-emblem.webp', heroTitle: 'About', heroAccent: 'The Covert Team',
    tagline: 'The people who make it happen, every day.' },
  { id: 'books',      label: 'Books',       badge: '2 Titles', icon: '/icons/about/about-books.svg',  img: '/about/about-books-rollover.webp',   cardBg: '/about/card-books.webp', href: '/about/books',
    heroImg: '/about/about-books-cover.webp', heroBg: '/about/about-hero-texture.webp', heroEmblem: '/about/about-books-hero.webp', heroEmblemWide: true, heroTitle: 'Books', heroAccent: 'by Anna Covert', tagline: 'Bestselling reads on marketing and the solar industry.' },
  { id: 'podcasts',   label: 'Podcasts',    badge: '2 Series', icon: '/icons/about/about-podcasts.svg', img: '/about/about-podcasts-rollover.webp', cardBg: '/about/card-podcasts.webp', href: '/about/podcasts',
    heroBg: '/about/about-hero-texture.webp', heroEmblem: '/about/about-anna-headshot.webp', heroEmblemFigure: true, heroTitle: 'Podcasts', heroAccent: 'with Anna Covert',
    tagline: 'Conversations on marketing, media, and solar.' },
  { id: 'otherbrands',label: 'Other Brands',badge: '4 Brands', icon: '/icons/about/about-otherbrands.svg',             img: '/about/about-otherbrands-rollover.webp', cardBg: '/about/card-otherbrands.webp', href: '/about/otherbrands',
    heroBg: '/about/about-otherbrands-hero.webp', tagline: 'Other ventures built by the Covert Communication team.' },
]

export const ABOUT_BOOKS = [
  {
    id: 'covert-code',
    title: 'The Covert Code',
    subtitle: 'Mastering the Art of Digital Marketing',
    author: 'Anna Covert',
    cover: '/about/about-books-cover.webp',
    badges: ['Forbes Books', 'Amazon Best Seller'],
    copy: 'A practical playbook for building and scaling a modern marketing agency, drawn from Anna Covert’s own experience growing Covert Communication.',
    buyHref: '#',
  },
  {
    id: 'solar-coaster',
    title: 'The Solar Coaster',
    subtitle: 'The Solar Industry’s Ultimate Playbook',
    author: 'Anna Covert',
    cover: '/about/about-books-cover.webp',
    badges: ['New!'],
    copy: 'A hands-on guide to marketing and growing a solar business, built on lessons from the front lines of a fast-moving industry.',
    buyHref: '#',
  },
]

export const ABOUT_PODCASTS = [
  {
    id: 'covert-code-podcast',
    title: 'The Covert Code Podcast',
    subscribers: 'Over 150,000+ Subscribers & growing!',
    copy: 'Anna Covert breaks down marketing strategy, brand building, and the business of agency life.',
    listenHref: '#',
  },
  {
    id: 'solar-coaster-podcast',
    title: 'The Solar Coaster Podcast',
    subscribers: 'Over 50,000+ Subscribers & growing!',
    copy: 'A look inside the solar industry, its ups and downs, and how to market and grow within it.',
    listenHref: '#',
  },
]

const BRAND_LOREM = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate'

export const ABOUT_BRANDS = [
  { id: 'trusting-solar-calculator', name: 'Trusting SolarCalculator', logo: '/about/brand-trusting-solar.webp',
    caption: 'CAPTION GOES HERE', copy: BRAND_LOREM, href: '#' },
  { id: 'mana', name: 'Mana', logo: '/about/brand-mana.webp',
    caption: 'CAPTION GOES HERE', copy: BRAND_LOREM, href: '#' },
  { id: 'switch-it-solar', name: 'Switch It Solar', logo: '/about/brand-switch-it.webp',
    caption: 'CAPTION GOES HERE', copy: BRAND_LOREM, href: '#' },
  { id: 'solar-assault', name: 'Solar Assault', logo: '/about/brand-solar-assault.webp',
    caption: 'CAPTION GOES HERE', copy: BRAND_LOREM, href: '#' },
  { id: 'reactium', name: 'Reactium', logo: '/about/brand-reactium.webp',
    caption: 'CAPTION GOES HERE', copy: BRAND_LOREM, href: '#' },
]

export const HOW_DID_YOU_HEAR = [
  { label: 'Please choose one', value: '' },
  { label: 'Online', value: 'online' },
  { label: 'Mail', value: 'mail' },
  { label: 'Family/Friend', value: 'familyfriend' },
  { label: 'Other', value: 'other' },
]

/* Labels are laid out at equal angles around the logo in App.jsx, so the
   order here is the order they appear going clockwise around the ring. */
export const HERO_PILLS = [
  { label: 'Digital Growth\nSEO / AEO / GEO' },
  { label: 'Programmatic' },
  { label: 'Technology Strategy\n& Engineering' },
  { label: 'Social Media' },
  { label: 'Fraud Prevention' },
  { label: 'Privacy & Compliance' },
  { label: 'Branding' },
  { label: 'Authority & Influence' },
]

/* ---------- THE LATEST ---------- */
/* Category order drives the filter-pill row on /the-latest.
   'All' is prepended in-page; each LATEST item's `category`
   must match one of these labels. */
export const LATEST_CATEGORIES = ['All', 'Books', 'Podcasts', 'Solar', 'Technology']

export const LATEST = [
  { id: "tipping-the-scale", slug: "tipping-the-scale-navigating-privacy-and-innovation-in-advertising", category: "Technology", title: "Tipping the Scale: Navigating Privacy and Innovation in Advertising", img: "https://thecovertcode.com/wp-content/uploads/2025/01/Ads.png" },
  { id: "3547-thecovertcode", slug: "episode-122-embrace-the-pilgrim-spirit", category: "Podcasts", title: "Episode 122 – Gideon Enok", img: "https://thecovertcode.com/wp-content/uploads/2026/07/Screenshot-2026-07-15-at-6.23.54-PM-1024x575.png" },
  { id: "3527-thecovertcode", slug: "gina-riley-why-being-qualified-isnt-enough-anymore-ep-121", category: "Podcasts", title: "Episode 121 – Gina Riley", img: "https://thecovertcode.com/wp-content/uploads/2026/07/COVERT-CODE-TITLES-1.png" },
  { id: "3508-thecovertcode", slug: "marty-fahncke-build-a-business-worth-selling", category: "Podcasts", title: "Episode 120 – Marty Fahncke", img: "https://thecovertcode.com/wp-content/uploads/2026/07/COVERT-CODE-TITLES.png" },
  { id: "3491-thecovertcode", slug: "episode-119-dr-annu-navani", category: "Podcasts", title: "Episode 119 – Dr. Annu Navani", img: "https://thecovertcode.com/wp-content/uploads/2026/06/COVERT-CODE-TITLES-1.png" },
  { id: "3495-thecovertcode", slug: "why-leaders-must-be-more-visible-vocal-and-vulnerable-to-win-consumer-trust", category: "Technology", title: "Why Leaders Must Be More Visible, Vocal, and Vulnerable to Win Consumer Trust", img: "https://thecovertcode.com/wp-content/uploads/2026/06/pexels-yankrukov-7793149-1024x683.jpg" },
  { id: "3477-thecovertcode", slug: "episode-118-charlene-rose", category: "Podcasts", title: "Episode 118 – Charlene Rose", img: "https://thecovertcode.com/wp-content/uploads/2026/06/COVERT-CODE-TITLES.png" },
  { id: "3455-thecovertcode", slug: "episode-117-dave-gulas", category: "Podcasts", title: "Episode 117 – Dave Gulas", img: "https://thecovertcode.com/wp-content/uploads/2026/06/dave-gulas-founder-led-selling-headshot-1024x819.jpg" },
  { id: "3443-thecovertcode", slug: "episode-116-rob-aquino", category: "Podcasts", title: "Episode 116 – Rob Aquino", img: "https://thecovertcode.com/wp-content/uploads/2026/06/8.png" },
  { id: "3439-thecovertcode", slug: "chatgpt-advertising-future-marketing", category: "Technology", title: "What ChatGPT Advertising Means for the Future of Digital Marketing", img: "https://thecovertcode.com/wp-content/uploads/2026/06/2.png" },
  { id: "3430-thecovertcode", slug: "episode-115-lou-chatta", category: "Podcasts", title: "Episode 115 – Lou Chatta", img: "https://thecovertcode.com/wp-content/uploads/2026/05/8.png" },
  { id: "1830-annacovert", slug: "why-leaders-must-be-more-visible-vocal-and-vulnerable-to-win-consumer-trust-annacovert", category: "Technology", title: "Why Leaders Must Be More Visible, Vocal, and Vulnerable to Win Consumer Trust", img: "https://annacovert.com/wp-content/uploads/2026/06/pexels-yankrukov-7793149-1024x683.jpg" },
  { id: "1744-annacovert", slug: "the-next-solar-marketing-shift-why-zero-click-search-changes-everything", category: "Solar", title: "The Next Solar Marketing Shift: Why Zero-Click Search Changes Everything", img: "https://annacovert.com/wp-content/uploads/2026/06/4eb6782d-f5be-423b-8dea-61e5337602ac.png" },
  { id: "1737-annacovert", slug: "chatgpt-ads-are-coming-why-business-leaders-need-an-ai-visibility-strategy-now", category: "Technology", title: "ChatGPT Ads Are Coming: Why Business Leaders Need an AI Visibility Strategy Now", img: "https://annacovert.com/wp-content/uploads/2026/06/1.png" },
  { id: "1694-annacovert", slug: "authority-as-a-growth-strategy-forbes-books-podcast", category: "Books", title: "The Covert Code Launches “Authority as a Growth Strategy” A Forbes Books special podcast series presented by The Covert Code", img: "https://annacovert.com/wp-content/uploads/2026/04/Screenshot-2026-04-20-at-2.57.06-PM.png" },
  { id: "1579-annacovert", slug: "the-covert-code-podcast-celebrates-100000-followers-and-100-episodes", category: "Podcasts", title: "The Covert Code Podcast Celebrates 100,000 Followers and 100 Episodes", img: "https://annacovert.com/wp-content/uploads/2026/01/Untitled-design-4.png" },
  { id: "1517-annacovert", slug: "the-covert-code-podcast-surpasses-45000-followers", category: "Podcasts", title: "The Covert Code Podcast Surpasses 45,000 Followers on YouTube", img: "https://annacovert.com/wp-content/uploads/2025/10/Untitled-design-1.png" },
  { id: "1492-annacovert", slug: "anna-covert-keynote-speaker-at-adwest-conference", category: "Technology", title: "Anna Covert, Keynote Speaker at 2025 AAF AdWest Conference", img: "https://annacovert.com/wp-content/uploads/2025/09/Untitled-design-29.png" },
  { id: "1373-annacovert", slug: "the-solar-coaster-is-the-newly-published-book-by-anna-covert", category: "Books", title: "The Solar Coaster is the Newly Published Book by Anna Covert", img: "https://annacovert.com/wp-content/uploads/2025/09/AC-PR-for-Websites.jpg" },
  { id: "1304-annacovert", slug: "anna-covert-to-lead-mission-driven-marketing-a-digital-marketing-101-workshop", category: "Technology", title: "Anna Covert to Lead “Mission-Driven Marketing: A Digital Marketing 101 Workshop”", img: "https://annacovert.com/wp-content/uploads/2025/08/Screenshot-2025-08-19-at-9.11.45-AM.png" },
  { id: "1252-annacovert", slug: "digimarcon-hawaii-2025-anna-covert", category: "Technology", title: "Anna Covert to Speak at DigiMarCon Hawaii", img: "https://annacovert.com/wp-content/uploads/2025/07/1753352053130.jpg" },
  { id: "3510-solarcoasterbook", slug: "the-patent-battle-behind-the-smart-grid-ep-46", category: "Solar", title: "The Patent Battle Behind the Smart Grid – EP 46", img: "https://solarcoasterbook.com/wp-content/uploads/2026/07/Solar-Coaster-Intro-1.png" },
  { id: "3506-solarcoasterbook", slug: "the-talent-bottleneck-ep-45", category: "Solar", title: "The Talent Bottleneck – EP 45", img: "https://solarcoasterbook.com/wp-content/uploads/2026/07/Solar-Coaster-Intro.png" },
  { id: "3496-solarcoasterbook", slug: "why-safe-harbor-and-domestic-content-are-reshaping-solar-finance", category: "Solar", title: "Why Safe Harbor and Domestic Content Are Reshaping Solar Finance – EP 44", img: "https://solarcoasterbook.com/wp-content/uploads/2026/06/Solar-Coaster-Intro-4.png" },
  { id: "3485-solarcoasterbook", slug: "the-solar-afterlife-what-happens-when-solar-farms-retire-ep-43", category: "Solar", title: "The Solar Afterlife: What Happens When Solar Farms Retire? – EP 43", img: "https://solarcoasterbook.com/wp-content/uploads/2026/06/Solar-Coaster-Intro-3.png" },
  { id: "3480-solarcoasterbook", slug: "made-in-america-the-solar-supply-chain-revolution-ep-42", category: "Solar", title: "Made in America: The Solar Supply Chain Revolution – EP 42", img: "https://solarcoasterbook.com/wp-content/uploads/2026/06/Solar-Coaster-Intro-2.png" },
  { id: "3475-solarcoasterbook", slug: "renewable-energys-new-reality-share-the-risk-or-miss-the-opportunity-ep-41", category: "Solar", title: "Renewable Energy’s New Reality: Share the Risk or Miss the Opportunity – EP 41", img: "https://solarcoasterbook.com/wp-content/uploads/2026/06/Solar-Coaster-Intro-1.png" },
  { id: "3470-solarcoasterbook", slug: "the-great-energy-divide-why-oil-volatility-is-accelerating-the-solar-revolution-ep-40", category: "Solar", title: "The Great Energy Divide: Why Oil Volatility Is Accelerating the Solar Revolution – EP 40", img: "https://solarcoasterbook.com/wp-content/uploads/2026/06/Solar-Coaster-Intro.png" },
  { id: "3457-solarcoasterbook", slug: "the-silent-saboteur-why-solar-is-really-a-30-year-bet-ep-39", category: "Solar", title: "The Silent Saboteur: Why Solar Is Really a 30-Year Bet – EP 39", img: "https://solarcoasterbook.com/wp-content/uploads/2026/05/Solar-Coaster-Intro-3.png" },
  { id: "3456-solarcoasterbook", slug: "the-solar-paradox-why-infrastructure-will-define-the-next-decade-ep-38", category: "Solar", title: "The Solar Paradox: Why Infrastructure Will Define the Next Decade – Ep 38", img: "https://solarcoasterbook.com/wp-content/uploads/2026/05/Solar-Coaster-Intro-2.png" },
  { id: "3455-solarcoasterbook", slug: "the-invisible-architects-behind-the-solar-revolution-ep-37", category: "Solar", title: "The Invisible Architects Behind the Solar Revolution – EP 37", img: "https://solarcoasterbook.com/wp-content/uploads/2026/05/Solar-Coaster-Intro-1.png" },
]

/* ---------- CASE STUDIES ---------- */
const CS_LOREM = 'We partnered end to end — strategy, brand, build, and growth — aligning every touchpoint around a single, measurable goal. From positioning and design system to a fast, SEO-ready site and an always-on acquisition engine, the work was built to convert and to scale.'

export const CASE_STUDIES = [
  {
    slug: 'wolf-river-construction',
    title: 'Wolf River Construction',
    tags: ['Branding', 'Web Development', 'WordPress', 'GoHighLevel', 'PostGrid'],
    excerpt: 'A Midwest roofing and exterior-renovation contractor rebranded and rebuilt on WordPress — with an interactive roofing calculator feeding an automated GoHighLevel and PostGrid follow-up engine.',
    cover: '/case-studies/wolf-river-construction/cover.png',
    description: 'Wolf River Construction is a Midwest roofing and exterior-renovation company that needed a digital presence as dependable as its craftsmanship. We built a bold, high-contrast brand and a conversion-focused WordPress site — anchored by an interactive roofing calculator and clear paths to a free quote — that positions Wolf River as a premium, GAF Master Elite contractor across residential, commercial, and solar work.\n\nBehind the scenes, we wired the site into GoHighLevel so every lead flows straight into an automated follow-up pipeline, and integrated PostGrid to trigger direct-mail outreach without manual effort. The result is a marketing engine that captures homeowners at the moment of intent and keeps Wolf River in front of them across both digital and print.',
    images: ['/case-studies/wolf-river-construction/1.png', '/case-studies/wolf-river-construction/2.png', '/case-studies/wolf-river-construction/3.png', '/case-studies/wolf-river-construction/4.png', '/case-studies/wolf-river-construction/5.png'],
  },
  {
    slug: 'northwind-saas',
    title: 'Northwind SaaS',
    tags: ['Web Design', 'SEO', 'Programmatic'],
    excerpt: 'A B2B SaaS marketing site rebuilt for speed and search — paired with an always-on programmatic engine.',
    cover: '/case-studies/northwind-saas/cover.svg',
    description: 'NORTHWIND is a B2B SaaS platform that needed a marketing site to match its ambition.\n\n' + CS_LOREM,
    images: ['/case-studies/northwind-saas/1.svg', '/case-studies/northwind-saas/2.svg', '/case-studies/northwind-saas/3.svg', '/case-studies/northwind-saas/4.svg'],
  },
  {
    slug: 'lumen-solar',
    title: 'Lumen Solar',
    tags: ['Branding', 'Web Development', 'Paid Social'],
    excerpt: 'A solar installer relaunched with a clean identity, a lead-gen site, and a paid social program that fills the pipeline.',
    cover: '/case-studies/lumen-solar/cover.svg',
    description: 'LUMEN SOLAR came to us to stand out in a crowded, fast-moving market.\n\n' + CS_LOREM,
    images: ['/case-studies/lumen-solar/1.svg', '/case-studies/lumen-solar/2.svg', '/case-studies/lumen-solar/3.svg', '/case-studies/lumen-solar/4.svg'],
  },
  {
    slug: 'meridian-health',
    title: 'Meridian Health',
    tags: ['UX/UI', 'Technology Consulting', 'SEO'],
    excerpt: 'A healthcare platform redesigned around patient clarity, accessibility, and organic discoverability.',
    cover: '/case-studies/meridian-health/cover.svg',
    description: 'MERIDIAN HEALTH needed a digital experience patients could trust at a glance.\n\n' + CS_LOREM,
    images: ['/case-studies/meridian-health/1.svg', '/case-studies/meridian-health/2.svg', '/case-studies/meridian-health/3.svg', '/case-studies/meridian-health/4.svg'],
  },
  {
    slug: 'cobalt-fintech',
    title: 'Cobalt Fintech',
    tags: ['Brand Building', 'SEM', 'Analytics'],
    excerpt: 'A fintech challenger positioned for its Series B — full rebrand, performance search, and a measurement stack that proves ROI.',
    cover: '/case-studies/cobalt-fintech/cover.svg',
    description: 'COBALT is a fintech challenger that needed to look and perform like a category leader.\n\n' + CS_LOREM,
    images: ['/case-studies/cobalt-fintech/1.svg', '/case-studies/cobalt-fintech/2.svg', '/case-studies/cobalt-fintech/3.svg', '/case-studies/cobalt-fintech/4.svg'],
  },
  {
    slug: 'harbor-retail',
    title: 'Harbor Retail',
    tags: ['Traditional Full Service', 'Social Media', 'Web'],
    excerpt: 'An omnichannel retail brand unified across print, broadcast, social, and a conversion-focused storefront.',
    cover: '/case-studies/harbor-retail/cover.svg',
    description: 'HARBOR RETAIL wanted one coherent brand across every channel its customers touch.\n\n' + CS_LOREM,
    images: ['/case-studies/harbor-retail/1.svg', '/case-studies/harbor-retail/2.svg', '/case-studies/harbor-retail/3.svg', '/case-studies/harbor-retail/4.svg'],
  },
]
