export const SERVICES = [
  { id: 'digital-growth',      title: 'Digital Growth',                     count: 7, img: '/categories/digital-growth.svg',      hoverImg: '/categories/digital-growth.svg',              icon: '/icons/brand-building.svg',
    cardSubs: ['SEO / AEO / GEO', 'Paid Search & AI Ads', 'Website Design', 'Email Marketing'],
    subs: ['SEO / AEO / GEO', 'Paid Search & AI Ads', 'Website Design', 'Email Marketing', 'Conversion Rate Optimization', 'Marketing Automation', 'Analytics & Attribution'] },
  { id: 'programmatic',        title: 'Programmatic',                       count: 7, img: '/categories/programmatic.webp',       hoverImg: '/services/svc-programmatic-rollover.webp',    icon: '/icons/programmatic.svg',
    cardSubs: ['Remarketing', 'Full-Funnel', 'Display', 'CTV / OTT'],
    subs: ['Remarketing', 'Full-Funnel', 'Display', 'CTV / OTT', 'Audience & Data Strategy', 'Creative Optimization', 'Native & Audio'] },
  { id: 'technology',          title: 'Technology Strategy & Engineering',  count: 7, img: '/categories/technology.webp',         hoverImg: '/services/svc-tech-rollover.webp',            icon: '/icons/tech.svg',
    cardSubs: ['Technology Audits', 'CRM & Automation', 'Custom Software', 'Reporting & Analytics'],
    subs: ['Technology Audits', 'CRM & Automation', 'Custom Software', 'Reporting & Analytics', 'Web Development', 'App Development', 'Integrations & APIs'] },
  { id: 'social',              title: 'Social Media',                       count: 7, img: '/categories/social.webp',             hoverImg: '/services/svc-social-rollover.webp',          icon: '/icons/social.svg',
    cardSubs: ['Social Strategy', 'Content Creation', 'Paid Social', 'Influencer Marketing'],
    subs: ['Social Strategy', 'Content Creation', 'Paid Social', 'Influencer Marketing', 'Community Management', 'Short-Form Video', 'Social Listening'] },
  { id: 'fraud',               title: 'Fraud Prevention',                   count: 7, img: '/categories/fraud.webp',              hoverImg: '/services/svc-fraud-rollover.webp',           icon: '/icons/fraud.svg',
    cardSubs: ['Ad Fraud', 'Click Fraud', 'Lead Fraud', 'Brand Safety'],
    subs: ['Ad Fraud', 'Click Fraud', 'Lead Fraud', 'Brand Safety', 'Bot & Traffic Filtering', 'Media Verification', 'Incident Response'] },
  { id: 'privacy-compliance',  title: 'Privacy & Compliance',               count: 7, img: '/categories/privacy-compliance.svg',  hoverImg: '/categories/privacy-compliance.svg',          icon: '/icons/trad-full-service.svg',
    cardSubs: ['Data Mapping', 'Consent Management', 'Consumer Requests', 'Privacy Audits'],
    subs: ['Data Mapping', 'Consent Management', 'Consumer Requests', 'Privacy Audits', 'Cookieless & First-Party Data', 'Accessibility (WCAG)', 'Policy & Governance'] },
  { id: 'branding',            title: 'Branding',                           count: 7, img: '/categories/brand-creation.webp',     hoverImg: '/services/svc-brand-creation-rollover.webp',  icon: '/icons/brand-creation.svg',
    cardSubs: ['Logo Design', 'Corporate Identity', 'Brand Guidelines', 'Business Collateral'],
    subs: ['Logo Design', 'Corporate Identity', 'Brand Guidelines', 'Business Collateral', 'Naming', 'Positioning & Messaging', 'Packaging Design'] },
  { id: 'authority-influence', title: 'Authority & Influence',              count: 7, img: '/categories/authority-influence.svg', hoverImg: '/categories/authority-influence.svg',         icon: '/icons/brand-specialties.svg',
    cardSubs: ['Personal Branding', 'Public Relations', 'Podcast Management', 'Author Services'],
    subs: ['Personal Branding', 'Public Relations', 'Podcast Management', 'Author Services', 'Thought Leadership', 'Speaking & Events', 'Awards & Recognition'] },
]

/* Mega-menu order. The panel is a 2-column grid that fills row-wise, so this
   array interleaves the two dropdown columns (left, right, left, right...). */
export const MEGA_SERVICES = [
  { id: 'digital-growth',      title: 'Digital Growth',                    count: 7, img: '/categories/digital-growth-menu.svg',      icon: '/icons/brand-building.svg' },
  { id: 'programmatic',        title: 'Programmatic',                      count: 7, img: '/services/svc-programmatic-rollover.webp',     icon: '/icons/programmatic.svg' },
  { id: 'technology',          title: 'Technology Strategy & Engineering', count: 7, img: '/services/svc-tech-rollover.webp',             icon: '/icons/tech.svg' },
  { id: 'social',              title: 'Social Media',                      count: 7, img: '/services/svc-social-rollover.webp',           icon: '/icons/social.svg' },
  { id: 'fraud',               title: 'Fraud Prevention',                  count: 7, img: '/services/svc-fraud-rollover.webp',            icon: '/icons/fraud.svg' },
  { id: 'privacy-compliance',  title: 'Privacy & Compliance',              count: 7, img: '/categories/privacy-compliance-menu.svg',  icon: '/icons/trad-full-service.svg' },
  { id: 'branding',            title: 'Branding',                          count: 7, img: '/services/svc-brand-creation-rollover.webp',   icon: '/icons/brand-creation.svg' },
  { id: 'authority-influence', title: 'Authority & Influence',             count: 7, img: '/categories/authority-influence-menu.svg', icon: '/icons/brand-specialties.svg' },
]

/* Rich, per-service detail content. Only services present here render the
   expanded alternating-feature layout; others fall back to the generic body. */
export const SERVICE_DETAILS = {
  'digital-growth': {
    hero: {
      eyebrow: 'Digital Growth',
      title: 'Digital Growth',
      lead: 'Search, site, and inbox working as one engine — visibility that compounds, traffic that converts, and customers who come back.',
      bg: '/services/brand-building/hero.webp',
      bottom: true,
      heroTitle: 'Digital',
      heroAccent: 'Growth',
    },
    intro: {
      title: 'Growth is a system, not a campaign',
      copy: 'We treat the funnel as one connected machine. Visibility, landing experience, lifecycle messaging, and measurement are instrumented end to end, then improved on a testing cadence that never stops.',
      stats: [
        { value: '+62%', label: 'Conversion lift' },
        { value: '−34%', label: 'Cost per acquisition' },
        { value: '248%', label: 'Organic lift' },
        { value: 'Weekly', label: 'Test velocity' },
      ],
    },
    features: [
      { id: 'seo-aeo-geo', kicker: '01', title: 'SEO / AEO / GEO', image: '/services/programmatic/seo.svg',
        copy: 'Organic visibility engineered for the way people search now — classic rankings, AI answer engines, and local intent handled as one discipline instead of three disconnected retainers.',
        points: ['Technical & Core Web Vitals', 'Answer-engine & schema data', 'Local & map-pack visibility'] },
      { id: 'paid-search', kicker: '02', title: 'Paid Search & AI Ads', image: '/services/programmatic/sem.svg',
        copy: 'Paid search that treats every keyword as a P&L line. Automated bidding, disciplined creative testing, and AI-driven ad formats pointed squarely at pipeline.',
        points: ['Automated bid strategy', 'AI & responsive ad formats', 'Conversion-first landing pages'] },
      { id: 'website-design', kicker: '03', title: 'Website Design', image: '/services/technology/web.svg',
        copy: 'Sites designed around the decision your visitor is trying to make. Fast, accessible, and built so the marketing team can update them without filing a ticket.',
        points: ['Conversion-led design', 'Core Web Vitals tuned', 'CMS your team can run'] },
      { id: 'email-marketing', kicker: '04', title: 'Email Marketing', image: '/services/brand-building/positioning.svg',
        copy: 'Owned channels that pay for themselves. Welcome, nurture, win-back, and post-purchase flows built around behavior instead of a blast calendar.',
        points: ['Flow architecture', 'Segmentation & triggers', 'Deliverability care'] },
      { id: 'cro', kicker: '05', title: 'Conversion Rate Optimization', image: '/services/brand-building/campaigns.svg',
        copy: 'Structured experimentation on the pages that matter most. Hypotheses grounded in session data and research, tested properly, shipped when they win.',
        points: ['Research & heuristics', 'A/B & multivariate tests', 'Win rollout & documentation'] },
      { id: 'automation', kicker: '06', title: 'Marketing Automation', image: '/services/technology/strategy.svg',
        copy: 'The plumbing behind personalized marketing at scale. We configure the platform, connect the data, and automate the handoffs your team is doing by hand.',
        points: ['Platform configuration', 'Lead scoring & routing', 'CRM & sales handoff'] },
      { id: 'analytics', kicker: '07', title: 'Analytics & Attribution', image: '/services/brand-building/analytics.svg',
        copy: 'Measurement you can defend in a board meeting. Clean tracking, a shared definition of a conversion, and attribution that reflects how buying actually happens.',
        points: ['Tracking & tag governance', 'Multi-touch attribution', 'Dashboards & reporting'] },
    ],
  },

  programmatic: {
    hero: {
      eyebrow: 'Programmatic Media',
      title: 'Programmatic',
      lead: 'Data-driven media that finds the right audience, in the right moment, across every screen — bought and optimized in real time by machines that never sleep.',
      bg: '/services/programmatic/hero.webp',
      bottom: true,
      heroAccent: 'Programmatic',
    },
    intro: {
      title: 'Precision at machine speed',
      copy: 'One always-on buying engine across display, video, connected TV, and audio. Every impression is measured, every bid is optimized, and every dollar is pointed at outcomes — not vanity metrics.',
      stats: [
        { value: '4.7×', label: 'Average ROAS' },
        { value: '<50ms', label: 'Bid decisioning' },
        { value: '96%', label: 'Viewable inventory' },
        { value: '24/7', label: 'Optimization' },
      ],
    },
    features: [
      { id: 'remarketing', kicker: '01', title: 'Remarketing', image: '/services/programmatic/geo.svg',
        copy: 'The people who already know you are the cheapest revenue you will ever buy. We segment by behavior and recency so the follow-up feels useful instead of relentless.',
        points: ['Behavioral segmentation', 'Frequency & recency caps', 'Dynamic product retargeting'] },
      { id: 'full-funnel', kicker: '02', title: 'Full-Funnel', image: '/services/programmatic/aeo.svg',
        copy: 'Awareness, consideration, and conversion planned as one flight with one budget. Spend moves to the stage that needs it instead of sitting in a locked line item.',
        points: ['Stage-based planning', 'Budget reallocation', 'Incrementality testing'] },
      { id: 'display', kicker: '03', title: 'Display', image: '/services/programmatic/sem.svg',
        copy: 'Curated inventory, verified placements, and creative built for the format. We buy attention that is actually viewable — and prove it.',
        points: ['Inventory curation', 'Viewability standards', 'Format-native creative'] },
      { id: 'ctv-ott', kicker: '04', title: 'CTV / OTT', image: '/services/trad/tvradio.svg',
        copy: 'Television bought like digital. Household-level targeting, cross-screen frequency control, and measurement that ties the impression to a real outcome.',
        points: ['Household targeting', 'Cross-screen frequency', 'Outcome measurement'] },
      { id: 'audience-data', kicker: '05', title: 'Audience & Data Strategy', image: '/services/brand-building/analytics.svg',
        copy: 'The targeting is only as good as the data behind it. We build audiences from your own signals, model look-alikes, and retire the segments that stop performing.',
        points: ['First-party audience builds', 'Look-alike modeling', 'Clean-room activation'] },
      { id: 'creative-optimization', kicker: '06', title: 'Creative Optimization', image: '/services/brand-building/campaigns.svg',
        copy: 'Creative is the biggest lever in programmatic. Dynamic assets, disciplined testing, and fast rotation keep performance from decaying mid-flight.',
        points: ['Dynamic creative optimization', 'Message & format testing', 'Fatigue monitoring'] },
      { id: 'native-audio', kicker: '07', title: 'Native & Audio', image: '/services/trad/print.svg',
        copy: 'Formats people choose to spend time with. Native placements that read like the page they sit on, and streaming audio that reaches commutes and workouts.',
        points: ['Native content placements', 'Streaming audio & podcast', 'Contextual alignment'] },
    ],
  },

  technology: {
    hero: {
      eyebrow: 'Technology Strategy & Engineering',
      title: 'Technology',
      lead: 'The engineering muscle behind great marketing — audited stacks, connected systems, and custom software built to scale cleanly.',
      bg: '/services/technology/hero.webp',
      bottom: true,
      heroTitle: 'Technology',
      heroAccent: 'Engineering',
    },
    intro: {
      title: 'Marketing needs a backbone',
      copy: 'Beautiful campaigns fall flat on slow, brittle tech. We audit what you run, connect what should talk to each other, and build what does not exist yet — pairing design sensibility with production-grade engineering.',
      stats: [
        { value: '98', label: 'Avg. Lighthouse' },
        { value: '3×', label: 'Faster load' },
        { value: '99.9%', label: 'Uptime' },
        { value: '0', label: 'Vendor lock-in' },
      ],
    },
    features: [
      { id: 'audits', kicker: '01', title: 'Technology Audits', image: '/services/technology/strategy.svg',
        copy: 'An honest read on the stack you already own — what is working, what is duplicated, and what is quietly costing you. You get a prioritized roadmap, not a vendor pitch.',
        points: ['Stack & spend review', 'Risk & debt assessment', 'Prioritized roadmap'] },
      { id: 'crm-automation', kicker: '02', title: 'CRM & Automation', image: '/services/brand-building/positioning.svg',
        copy: 'The system of record your revenue team actually trusts. Clean objects, sane routing, and automation that removes the manual steps instead of hiding them.',
        points: ['CRM implementation & cleanup', 'Lifecycle automation', 'Sales & marketing handoff'] },
      { id: 'custom-software', kicker: '03', title: 'Custom Software', image: '/services/technology/app.svg',
        copy: 'When off-the-shelf stops fitting, we build. Internal tools, customer portals, and products shipped by a team that has to maintain what it writes.',
        points: ['Web & mobile products', 'Internal tooling', 'Maintainable, documented code'] },
      { id: 'reporting', kicker: '04', title: 'Reporting & Analytics', image: '/services/brand-building/analytics.svg',
        copy: 'One number, one definition, one dashboard. We model the data properly so finance, marketing, and sales stop arguing about whose report is right.',
        points: ['Data modeling & warehousing', 'Executive dashboards', 'Automated reporting'] },
      { id: 'web', kicker: '05', title: 'Web Development', image: '/services/technology/web.svg',
        copy: 'Fast, accessible, conversion-focused sites built on modern frameworks. We obsess over Core Web Vitals so your marketing spend lands on pages that perform.',
        points: ['Modern JS frameworks', 'Core Web Vitals tuned', 'Headless & CMS integration'] },
      { id: 'app', kicker: '06', title: 'App Development', image: '/services/brand-specialties/video.svg',
        copy: 'Native and cross-platform apps that feel effortless. From first wireframe to store launch, we ship products your customers keep coming back to.',
        points: ['iOS & Android', 'Cross-platform builds', 'Analytics & push baked in'] },
      { id: 'integrations', kicker: '07', title: 'Integrations & APIs', image: '/services/brand-specialties/packaging.svg',
        copy: 'The connective tissue between your CRM, commerce, ad platforms, and internal tools. Well-documented APIs and integrations that stop the copy-paste work.',
        points: ['API design & docs', 'Third-party integrations', 'Webhooks & sync jobs'] },
    ],
  },

  social: {
    hero: {
      eyebrow: 'Social Media',
      title: 'Social Media',
      lead: 'Scroll-stopping content and paid strategy that turn followers into a community — and a community into customers.',
      bg: '/services/social/hero.webp',
      bottom: true,
      heroTitle: 'Social',
      heroAccent: 'Media',
    },
    intro: {
      title: 'Culture moves fast. So do we.',
      copy: 'We live where your audience lives. From thumb-stopping creative to precision paid targeting and always-on community care, we build social presence that compounds.',
      stats: [
        { value: '3.9×', label: 'Paid ROAS' },
        { value: '+180%', label: 'Engagement' },
        { value: '12M', label: 'Monthly reach' },
        { value: '<1h', label: 'Response time' },
      ],
    },
    features: [
      { id: 'strategy', kicker: '01', title: 'Social Strategy', image: '/services/brand-building/strategy.svg',
        copy: 'Which platforms, which formats, which cadence — decided from your audience and goals rather than from what everyone else is posting.',
        points: ['Channel & audience mapping', 'Content pillars', 'Cadence & measurement plan'] },
      { id: 'content', kicker: '02', title: 'Content Creation', image: '/services/social/content.svg',
        copy: 'Short-form video, motion graphics, and editorial made for the feed. We produce at the pace platforms demand without ever cutting the craft.',
        points: ['Short-form video', 'Motion & graphics', 'Editorial calendars'] },
      { id: 'paid', kicker: '03', title: 'Paid Social', image: '/services/social/paid.svg',
        copy: 'Full-funnel paid campaigns across Meta, TikTok, and LinkedIn. Sharp targeting, relentless creative testing, and budgets pointed squarely at return.',
        points: ['Full-funnel targeting', 'Creative testing', 'ROAS optimization'] },
      { id: 'influencer', kicker: '04', title: 'Influencer Marketing', image: '/services/social/influencer.svg',
        copy: 'The right creators, the right message, real results. We source, vet, and manage partnerships that borrow trust you can’t buy with ad spend.',
        points: ['Creator sourcing', 'Campaign management', 'Authenticity & reach'] },
      { id: 'community', kicker: '05', title: 'Community Management', image: '/services/social/community.svg',
        copy: 'Real conversations, handled with care. We moderate, engage, and nurture the people around your brand so goodwill turns into loyalty.',
        points: ['Daily engagement', 'Moderation & care', 'Community growth'] },
      { id: 'short-form', kicker: '06', title: 'Short-Form Video', image: '/services/brand-specialties/video.svg',
        copy: 'Vertical video built for the platform it lives on. Concepted, shot, and cut in volume so the algorithm always has something new to reward.',
        points: ['Concept & scripting', 'In-house production', 'Platform-native edits'] },
      { id: 'listening', kicker: '07', title: 'Social Listening', image: '/services/brand-building/analytics.svg',
        copy: 'What people say when you are not in the room is the most useful research you own. We monitor sentiment, spot issues early, and feed the findings back into strategy.',
        points: ['Sentiment & share of voice', 'Competitive monitoring', 'Early issue detection'] },
    ],
  },

  fraud: {
    hero: {
      eyebrow: 'Fraud Prevention',
      title: 'Fraud Prevention',
      lead: 'Every dollar of ad spend defended. We hunt bots, block invalid traffic, and keep your brand out of the wrong places — before the damage is done.',
      bg: '/services/fraud/hero.webp',
      bottom: true,
      heroTitle: 'Fraud',
      heroAccent: 'Prevention',
    },
    intro: {
      title: 'Real people. Real placements.',
      copy: 'Up to a third of digital ad spend is lost to fraud and waste. We sit between your budget and the open web, filtering invalid traffic in real time and guarding where your brand shows up.',
      stats: [
        { value: '−92%', label: 'Wasted spend' },
        { value: '99.6%', label: 'Valid traffic' },
        { value: 'Real-time', label: 'Pre-bid filtering' },
        { value: '24/7', label: 'Monitoring' },
      ],
    },
    features: [
      { id: 'ad-fraud', kicker: '01', title: 'Ad Fraud', image: '/services/fraud/addetection.svg',
        copy: 'Pre-bid and post-bid filtering that stops bots and invalid traffic cold. We score every impression so your money reaches humans, not scripts.',
        points: ['Bot & IVT detection', 'Pre-bid filtering', 'Spend recovery'] },
      { id: 'click-fraud', kicker: '02', title: 'Click Fraud', image: '/services/fraud/clickfraud.svg',
        copy: 'Anomaly detection that flags and blocks fraudulent clicks in real time — protecting your PPC budgets from competitors, click farms, and automated abuse.',
        points: ['Anomaly detection', 'IP & device blocking', 'Automated refunds'] },
      { id: 'lead-fraud', kicker: '03', title: 'Lead Fraud', image: '/services/trad/directmail.svg',
        copy: 'Fake forms and recycled leads poison your CRM and your cost-per-lead math. We validate at the point of capture so sales works real inquiries only.',
        points: ['Form & identity validation', 'Duplicate & recycled detection', 'Partner lead scoring'] },
      { id: 'brand-safety', kicker: '04', title: 'Brand Safety', image: '/services/fraud/brandsafety.svg',
        copy: 'Contextual controls and curated inventory keep your brand away from content that could harm it. You choose the company your ads keep.',
        points: ['Contextual controls', 'Inventory whitelisting', 'Reputation protection'] },
      { id: 'bot-filtering', kicker: '05', title: 'Bot & Traffic Filtering', image: '/services/brand-building/analytics.svg',
        copy: 'Not all traffic deserves your budget. We fingerprint sessions, separate automation from people, and keep the junk out of your funnel and your data.',
        points: ['Session fingerprinting', 'Data-center & proxy blocking', 'Clean analytics'] },
      { id: 'verification', kicker: '06', title: 'Media Verification', image: '/services/brand-specialties/photography.svg',
        copy: 'Independent proof that your ads ran where and how they were bought. Viewability, geography, and placement verified against what the invoice claims.',
        points: ['Viewability & geo checks', 'Placement verification', 'Vendor reconciliation'] },
      { id: 'incident', kicker: '07', title: 'Incident Response', image: '/services/brand-building/strategy.svg',
        copy: 'When something breaks through, speed matters. We contain the exposure, document the trail, and pursue makegoods so the loss does not become permanent.',
        points: ['Containment & rollback', 'Forensic reporting', 'Makegood recovery'] },
    ],
  },

  'privacy-compliance': {
    hero: {
      eyebrow: 'Privacy & Compliance',
      title: 'Privacy & Compliance',
      lead: 'Marketing that holds up under scrutiny — data mapped, consent handled properly, and consumer requests answered on the clock.',
      bg: '/services/trad/hero.webp',
      bottom: true,
      heroTitle: 'Privacy &',
      heroAccent: 'Compliance',
    },
    intro: {
      title: 'Trust is the new targeting',
      copy: 'Privacy rules keep tightening and third-party signal keeps shrinking. We help you collect less, use it better, and document every step — so growth never depends on data you should not have had.',
      stats: [
        { value: '100%', label: 'Consent coverage' },
        { value: '48h', label: 'Request turnaround' },
        { value: 'WCAG 2.2', label: 'Accessibility target' },
        { value: '0', label: 'Surprise findings' },
      ],
    },
    features: [
      { id: 'data-mapping', kicker: '01', title: 'Data Mapping', image: '/services/trad/print.svg',
        copy: 'You cannot protect what you cannot find. We inventory every system, flow, and vendor touching personal data and put it on one map your team can maintain.',
        points: ['System & vendor inventory', 'Data-flow diagrams', 'Retention schedules'] },
      { id: 'consent', kicker: '02', title: 'Consent Management', image: '/services/trad/directmail.svg',
        copy: 'Consent that is honored downstream, not just displayed. We implement the banner, wire it to your tags, and prove the signal reaches every vendor.',
        points: ['CMP implementation', 'Tag & vendor gating', 'Consent-signal QA'] },
      { id: 'consumer-requests', kicker: '03', title: 'Consumer Requests', image: '/services/trad/pr.svg',
        copy: 'Access, deletion, and opt-out requests handled as a routine workflow with a clock on it — verified, fulfilled across systems, and logged for the regulator.',
        points: ['Intake & identity verification', 'Cross-system fulfillment', 'Audit-ready logging'] },
      { id: 'privacy-audits', kicker: '04', title: 'Privacy Audits', image: '/services/fraud/brandsafety.svg',
        copy: 'A standing review of what you collect and how it is used, measured against the regulations that actually apply to you — with fixes ranked by real risk.',
        points: ['Regulatory gap analysis', 'Vendor risk assessment', 'Remediation roadmap'] },
      { id: 'first-party', kicker: '05', title: 'Cookieless & First-Party Data', image: '/services/trad/events.svg',
        copy: 'Measurement and targeting that survive signal loss. Server-side collection, modeled conversions, and durable first-party identity built on real consent.',
        points: ['Server-side tracking', 'Modeled conversions', 'Identity & clean rooms'] },
      { id: 'accessibility', kicker: '06', title: 'Accessibility (WCAG)', image: '/services/trad/tvradio.svg',
        copy: 'Digital experiences everyone can use — audited against WCAG, fixed in the code, and re-tested with assistive technology rather than a scanner alone.',
        points: ['Automated & manual audits', 'Remediation with engineering', 'VPAT & documentation'] },
      { id: 'governance', kicker: '07', title: 'Policy & Governance', image: '/services/trad/ooh.svg',
        copy: 'The policies, notices, and internal ownership that keep the program running after the project ends — written in language your team will actually follow.',
        points: ['Policy & notice drafting', 'Roles & accountability', 'Team training'] },
    ],
  },

  branding: {
    hero: {
      eyebrow: 'Branding',
      title: 'Branding',
      lead: 'The identity, language, and system that make a company recognizable in a second — and trusted for a decade.',
      bg: '/services/brand-creation/hero.webp',
      bottom: true,
      heroAccent: 'Branding',
    },
    intro: {
      title: 'Built to be remembered',
      copy: 'A brand is not a logo — it is every decision that makes you look and sound like yourself. We define the position, design the system, and document it so the whole organization can use it without us in the room.',
      stats: [
        { value: '100%', label: 'Ownable assets' },
        { value: '2×', label: 'Recall lift' },
        { value: '360°', label: 'Touchpoint coverage' },
        { value: '1', label: 'Source of truth' },
      ],
    },
    features: [
      { id: 'logo-design', kicker: '01', title: 'Logo Design', image: '/services/brand-creation/logo.svg',
        copy: 'Marks that hold up at any size, in any context. We design the full family — primary, secondary, and marque — with the type, color, and grid that surround it.',
        points: ['Primary & secondary marks', 'Type, color & grid', 'Full asset delivery'] },
      { id: 'corporate-identity', kicker: '02', title: 'Corporate Identity', image: '/services/brand-creation/identity.svg',
        copy: 'A complete visual and verbal identity built from your strategy, not from a trend board. Distinct, durable, and workable across every medium you use.',
        points: ['Identity concepting', 'Visual & verbal system', 'Application design'] },
      { id: 'brand-guidelines', kicker: '03', title: 'Brand Guidelines', image: '/services/brand-creation/guidelines.svg',
        copy: 'The rulebook that keeps everything consistent once the launch excitement fades. Clear, illustrated, and written for the people who actually use it.',
        points: ['Usage rules & examples', 'Voice & tone guidance', 'Team onboarding'] },
      { id: 'collateral', kicker: '04', title: 'Business Collateral', image: '/services/trad/print.svg',
        copy: 'Every day-to-day asset on brand and ready to use — decks, one-pagers, stationery, signage, and templates your team can fill in without breaking the system.',
        points: ['Decks & sales one-pagers', 'Stationery & signage', 'Editable templates'] },
      { id: 'naming', kicker: '05', title: 'Naming', image: '/services/brand-specialties/copywriting.svg',
        copy: 'Names for companies, products, and programs — generated widely, filtered hard, and checked for the legal and domain reality before you fall in love.',
        points: ['Naming territories', 'Linguistic screening', 'Trademark & domain checks'] },
      { id: 'positioning', kicker: '06', title: 'Positioning & Messaging', image: '/services/brand-building/positioning.svg',
        copy: 'The sentence you want to own, and the proof behind it. We define the audience, the competitive white space, and the message hierarchy that ladders to it.',
        points: ['Audience & category research', 'Positioning statement', 'Message hierarchy'] },
      { id: 'packaging', kicker: '07', title: 'Packaging Design', image: '/services/brand-specialties/packaging.svg',
        copy: 'Design that earns the pick-up on a crowded shelf and survives the unboxing photo. Structure, substrate, and hierarchy handled together.',
        points: ['Structural & label design', 'Shelf-impact testing', 'Print-ready production'] },
    ],
  },

  'authority-influence': {
    hero: {
      eyebrow: 'Authority & Influence',
      title: 'Authority & Influence',
      lead: 'Reputation you cannot buy with media spend — earned coverage, a credible personal brand, and a point of view the market repeats back to you.',
      bg: '/services/brand-specialties/hero.webp',
      bottom: true,
      heroTitle: 'Authority &',
      heroAccent: 'Influence',
    },
    intro: {
      title: 'Be the name people cite',
      copy: 'Buyers check you out long before they talk to you. We build the signals they find — press, podcasts, books, panels, and executive presence — into a program that runs on a calendar, not on luck.',
      stats: [
        { value: '4×', label: 'Earned mentions' },
        { value: '+70%', label: 'Branded search' },
        { value: '30+', label: 'Placements a year' },
        { value: 'Tier 1', label: 'Media relationships' },
      ],
    },
    features: [
      { id: 'personal-branding', kicker: '01', title: 'Personal Branding', image: '/services/brand-specialties/activation.svg',
        copy: 'Founders and executives as credible, human voices. We shape the narrative, build the publishing habit, and protect the time it takes to sustain it.',
        points: ['Narrative & platform', 'Social & LinkedIn cadence', 'Media training'] },
      { id: 'public-relations', kicker: '02', title: 'Public Relations', image: '/services/trad/pr.svg',
        copy: 'Story-driven media relations with the reporters who cover your category. Fewer, better pitches — plus the crisis plan you hope never to use.',
        points: ['Media relations & pitching', 'Announcement planning', 'Crisis communications'] },
      { id: 'podcast-management', kicker: '03', title: 'Podcast Management', image: '/services/social/influencer.svg',
        copy: 'A show that runs without eating your week. We produce, book, edit, and cut every episode down into the clips that carry it everywhere else.',
        points: ['Production & editing', 'Guest booking', 'Clip & distribution engine'] },
      { id: 'author-services', kicker: '04', title: 'Author Services', image: '/services/brand-specialties/copywriting.svg',
        copy: 'From manuscript to launch. Editorial support, publishing strategy, and the campaign that puts the book in front of the audience it was written for.',
        points: ['Editorial & ghostwriting', 'Publishing strategy', 'Launch campaigns'] },
      { id: 'thought-leadership', kicker: '05', title: 'Thought Leadership', image: '/services/brand-specialties/experiential.svg',
        copy: 'A defensible point of view, published consistently. We find the argument only you can make and turn it into research, bylines, and talks worth quoting.',
        points: ['POV development', 'Original research', 'Byline & op-ed program'] },
      { id: 'speaking', kicker: '06', title: 'Speaking & Events', image: '/services/trad/events.svg',
        copy: 'Stages that put your team in front of the right room. We source the calls for papers, shape the abstracts, and rehearse the talk until it lands.',
        points: ['Speaker sourcing & CFPs', 'Talk development', 'On-site amplification'] },
      { id: 'awards', kicker: '07', title: 'Awards & Recognition', image: '/services/brand-specialties/sponsorship.svg',
        copy: 'Third-party validation, pursued deliberately. We pick the awards and lists worth winning, write the entries, and make the wins do real marketing work.',
        points: ['Award program selection', 'Entry writing', 'Win amplification'] },
    ],
  },
}

export const MEGA_ABOUT = [
  { id: 'covertcom',  label: 'Covert Communication', icon: '/icons/about/about-covertcom.svg',    img: '/about/about-covertcom-rollover.webp',   cardBg: '/about/about-covertcom-rollover.webp', href: '/about/covertcom',
    heroImg: '/about/about-covertcom-emblem.webp', heroBg: '/about/about-hero-texture.webp', heroEmblem: '/about/about-hero-emblem.webp', tagline: 'The full-service agency behind the brand.' },
  { id: 'anna',       label: 'Anna Covert',           icon: '/icons/about/about-anna.png',  img: '/about/about-anna-rollover.webp',        cardBg: '/about/card-anna.webp', href: '/about/anna',
    heroImg: '/about/about-anna-emblem.webp', heroBg: '/about/about-hero-texture.webp', heroEmblem: '/about/about-anna-hero-emblem.webp', heroEmblemSharp: true, figure: '/about/about-anna-figure.webp', photo: '/about/about-anna-photo.webp', tagline: 'Founder, author, and the voice behind Covert Communication.' },
  { id: 'covertteam',label: 'The Covert Team',        icon: '/icons/about/about-covertteam.svg',           img: '/about/about-covertteam-rollover.webp',  cardBg: '/about/card-covertteam.webp', href: '/about/covertteam',
    heroBg: '/about/about-hero-texture.webp', heroEmblem: '/about/about-hero-emblem.webp', heroTitle: 'About', heroAccent: 'The Covert Team',
    tagline: 'The people who make it happen, every day.' },
  { id: 'books',      label: 'Books',       badge: '2 Titles', icon: '/icons/about/about-books.svg',  img: '/about/about-books-rollover.webp',   cardBg: '/about/card-books.webp', href: '/about/books',
    heroImg: '/about/about-books-cover.webp', heroBg: '/about/about-hero-texture.webp', heroEmblem: '/about/about-books-hero.webp', heroEmblemWide: true, heroTitle: 'Books', heroAccent: 'by Anna Covert', tagline: 'Bestselling reads on marketing and the solar industry.' },
  { id: 'podcasts',   label: 'Podcasts',    badge: '2 Series', icon: '/icons/about/about-podcasts.svg', img: '/about/about-podcasts-rollover.webp', cardBg: '/about/card-podcasts.webp', href: '/about/podcasts',
    heroBg: '/about/about-hero-texture.webp', heroEmblem: '/about/about-anna-headshot.webp', heroEmblemFigure: true, heroTitle: 'Podcasts', heroAccent: 'with Anna Covert',
    tagline: 'Conversations on marketing, media, and solar.' },
  { id: 'otherbrands',label: 'Other Brands',badge: '4 Brands', icon: '/icons/about/about-otherbrands.svg',             img: '/about/about-otherbrands-rollover.webp', cardBg: '/about/card-otherbrands.webp', href: '/about/otherbrands',
    heroBg: '/about/about-otherbrands-hero.webp', tagline: 'Other ventures built by the Covert Communication team.' },
]

export const ABOUT_BOOKS = [
  {
    id: 'covert-code',
    title: 'The Covert Code',
    subtitle: 'Mastering the Art of Digital Marketing',
    author: 'Anna Covert',
    cover: '/about/about-books-cover.webp',
    badges: ['Forbes Books', 'Amazon Best Seller'],
    copy: 'A practical playbook for building and scaling a modern marketing agency, drawn from Anna Covert’s own experience growing Covert Communication.',
    buyHref: '#',
  },
  {
    id: 'solar-coaster',
    title: 'The Solar Coaster',
    subtitle: 'The Solar Industry’s Ultimate Playbook',
    author: 'Anna Covert',
    cover: '/about/about-books-cover.webp',
    badges: ['New!'],
    copy: 'A hands-on guide to marketing and growing a solar business, built on lessons from the front lines of a fast-moving industry.',
    buyHref: '#',
  },
]

export const ABOUT_PODCASTS = [
  {
    id: 'covert-code-podcast',
    title: 'The Covert Code Podcast',
    subscribers: 'Over 150,000+ Subscribers & growing!',
    copy: 'Anna Covert breaks down marketing strategy, brand building, and the business of agency life.',
    listenHref: '#',
  },
  {
    id: 'solar-coaster-podcast',
    title: 'The Solar Coaster Podcast',
    subscribers: 'Over 50,000+ Subscribers & growing!',
    copy: 'A look inside the solar industry, its ups and downs, and how to market and grow within it.',
    listenHref: '#',
  },
]

const BRAND_LOREM = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate'

export const ABOUT_BRANDS = [
  { id: 'trusting-solar-calculator', name: 'Trusting SolarCalculator', logo: '/about/brand-trusting-solar.webp',
    caption: 'CAPTION GOES HERE', copy: BRAND_LOREM, href: '#' },
  { id: 'mana', name: 'Mana', logo: '/about/brand-mana.webp',
    caption: 'CAPTION GOES HERE', copy: BRAND_LOREM, href: '#' },
  { id: 'switch-it-solar', name: 'Switch It Solar', logo: '/about/brand-switch-it.webp',
    caption: 'CAPTION GOES HERE', copy: BRAND_LOREM, href: '#' },
  { id: 'solar-assault', name: 'Solar Assault', logo: '/about/brand-solar-assault.webp',
    caption: 'CAPTION GOES HERE', copy: BRAND_LOREM, href: '#' },
  { id: 'reactium', name: 'Reactium', logo: '/about/brand-reactium.webp',
    caption: 'CAPTION GOES HERE', copy: BRAND_LOREM, href: '#' },
]

export const HOW_DID_YOU_HEAR = [
  { label: 'Please choose one', value: '' },
  { label: 'Online', value: 'online' },
  { label: 'Mail', value: 'mail' },
  { label: 'Family/Friend', value: 'familyfriend' },
  { label: 'Other', value: 'other' },
]

/* Labels are laid out at equal angles around the logo in App.jsx, so the
   order here is the order they appear going clockwise around the ring. */
export const HERO_PILLS = [
  { label: 'Digital Growth\nSEO / AEO / GEO' },
  { label: 'Programmatic' },
  { label: 'Technology Strategy\n& Engineering' },
  { label: 'Social Media' },
  { label: 'Fraud Prevention' },
  { label: 'Privacy & Compliance' },
  { label: 'Branding' },
  { label: 'Authority & Influence' },
]

/* ---------- THE LATEST ---------- */
/* Category order drives the filter-pill row on /the-latest.
   'All' is prepended in-page; each LATEST item's `category`
   must match one of these labels. */
export const LATEST_CATEGORIES = ['All', 'Books', 'Podcasts', 'Solar', 'Technology']

export const LATEST = [
  { id: "tipping-the-scale", slug: "tipping-the-scale-navigating-privacy-and-innovation-in-advertising", category: "Technology", title: "Tipping the Scale: Navigating Privacy and Innovation in Advertising", img: "https://thecovertcode.com/wp-content/uploads/2025/01/Ads.png" },
  { id: "3547-thecovertcode", slug: "episode-122-embrace-the-pilgrim-spirit", category: "Podcasts", title: "Episode 122 – Gideon Enok", img: "https://thecovertcode.com/wp-content/uploads/2026/07/Screenshot-2026-07-15-at-6.23.54-PM-1024x575.png" },
  { id: "3527-thecovertcode", slug: "gina-riley-why-being-qualified-isnt-enough-anymore-ep-121", category: "Podcasts", title: "Episode 121 – Gina Riley", img: "https://thecovertcode.com/wp-content/uploads/2026/07/COVERT-CODE-TITLES-1.png" },
  { id: "3508-thecovertcode", slug: "marty-fahncke-build-a-business-worth-selling", category: "Podcasts", title: "Episode 120 – Marty Fahncke", img: "https://thecovertcode.com/wp-content/uploads/2026/07/COVERT-CODE-TITLES.png" },
  { id: "3491-thecovertcode", slug: "episode-119-dr-annu-navani", category: "Podcasts", title: "Episode 119 – Dr. Annu Navani", img: "https://thecovertcode.com/wp-content/uploads/2026/06/COVERT-CODE-TITLES-1.png" },
  { id: "3495-thecovertcode", slug: "why-leaders-must-be-more-visible-vocal-and-vulnerable-to-win-consumer-trust", category: "Technology", title: "Why Leaders Must Be More Visible, Vocal, and Vulnerable to Win Consumer Trust", img: "https://thecovertcode.com/wp-content/uploads/2026/06/pexels-yankrukov-7793149-1024x683.jpg" },
  { id: "3477-thecovertcode", slug: "episode-118-charlene-rose", category: "Podcasts", title: "Episode 118 – Charlene Rose", img: "https://thecovertcode.com/wp-content/uploads/2026/06/COVERT-CODE-TITLES.png" },
  { id: "3455-thecovertcode", slug: "episode-117-dave-gulas", category: "Podcasts", title: "Episode 117 – Dave Gulas", img: "https://thecovertcode.com/wp-content/uploads/2026/06/dave-gulas-founder-led-selling-headshot-1024x819.jpg" },
  { id: "3443-thecovertcode", slug: "episode-116-rob-aquino", category: "Podcasts", title: "Episode 116 – Rob Aquino", img: "https://thecovertcode.com/wp-content/uploads/2026/06/8.png" },
  { id: "3439-thecovertcode", slug: "chatgpt-advertising-future-marketing", category: "Technology", title: "What ChatGPT Advertising Means for the Future of Digital Marketing", img: "https://thecovertcode.com/wp-content/uploads/2026/06/2.png" },
  { id: "3430-thecovertcode", slug: "episode-115-lou-chatta", category: "Podcasts", title: "Episode 115 – Lou Chatta", img: "https://thecovertcode.com/wp-content/uploads/2026/05/8.png" },
  { id: "1830-annacovert", slug: "why-leaders-must-be-more-visible-vocal-and-vulnerable-to-win-consumer-trust-annacovert", category: "Technology", title: "Why Leaders Must Be More Visible, Vocal, and Vulnerable to Win Consumer Trust", img: "https://annacovert.com/wp-content/uploads/2026/06/pexels-yankrukov-7793149-1024x683.jpg" },
  { id: "1744-annacovert", slug: "the-next-solar-marketing-shift-why-zero-click-search-changes-everything", category: "Solar", title: "The Next Solar Marketing Shift: Why Zero-Click Search Changes Everything", img: "https://annacovert.com/wp-content/uploads/2026/06/4eb6782d-f5be-423b-8dea-61e5337602ac.png" },
  { id: "1737-annacovert", slug: "chatgpt-ads-are-coming-why-business-leaders-need-an-ai-visibility-strategy-now", category: "Technology", title: "ChatGPT Ads Are Coming: Why Business Leaders Need an AI Visibility Strategy Now", img: "https://annacovert.com/wp-content/uploads/2026/06/1.png" },
  { id: "1694-annacovert", slug: "authority-as-a-growth-strategy-forbes-books-podcast", category: "Books", title: "The Covert Code Launches “Authority as a Growth Strategy” A Forbes Books special podcast series presented by The Covert Code", img: "https://annacovert.com/wp-content/uploads/2026/04/Screenshot-2026-04-20-at-2.57.06-PM.png" },
  { id: "1579-annacovert", slug: "the-covert-code-podcast-celebrates-100000-followers-and-100-episodes", category: "Podcasts", title: "The Covert Code Podcast Celebrates 100,000 Followers and 100 Episodes", img: "https://annacovert.com/wp-content/uploads/2026/01/Untitled-design-4.png" },
  { id: "1517-annacovert", slug: "the-covert-code-podcast-surpasses-45000-followers", category: "Podcasts", title: "The Covert Code Podcast Surpasses 45,000 Followers on YouTube", img: "https://annacovert.com/wp-content/uploads/2025/10/Untitled-design-1.png" },
  { id: "1492-annacovert", slug: "anna-covert-keynote-speaker-at-adwest-conference", category: "Technology", title: "Anna Covert, Keynote Speaker at 2025 AAF AdWest Conference", img: "https://annacovert.com/wp-content/uploads/2025/09/Untitled-design-29.png" },
  { id: "1373-annacovert", slug: "the-solar-coaster-is-the-newly-published-book-by-anna-covert", category: "Books", title: "The Solar Coaster is the Newly Published Book by Anna Covert", img: "https://annacovert.com/wp-content/uploads/2025/09/AC-PR-for-Websites.jpg" },
  { id: "1304-annacovert", slug: "anna-covert-to-lead-mission-driven-marketing-a-digital-marketing-101-workshop", category: "Technology", title: "Anna Covert to Lead “Mission-Driven Marketing: A Digital Marketing 101 Workshop”", img: "https://annacovert.com/wp-content/uploads/2025/08/Screenshot-2025-08-19-at-9.11.45-AM.png" },
  { id: "1252-annacovert", slug: "digimarcon-hawaii-2025-anna-covert", category: "Technology", title: "Anna Covert to Speak at DigiMarCon Hawaii", img: "https://annacovert.com/wp-content/uploads/2025/07/1753352053130.jpg" },
  { id: "3510-solarcoasterbook", slug: "the-patent-battle-behind-the-smart-grid-ep-46", category: "Solar", title: "The Patent Battle Behind the Smart Grid – EP 46", img: "https://solarcoasterbook.com/wp-content/uploads/2026/07/Solar-Coaster-Intro-1.png" },
  { id: "3506-solarcoasterbook", slug: "the-talent-bottleneck-ep-45", category: "Solar", title: "The Talent Bottleneck – EP 45", img: "https://solarcoasterbook.com/wp-content/uploads/2026/07/Solar-Coaster-Intro.png" },
  { id: "3496-solarcoasterbook", slug: "why-safe-harbor-and-domestic-content-are-reshaping-solar-finance", category: "Solar", title: "Why Safe Harbor and Domestic Content Are Reshaping Solar Finance – EP 44", img: "https://solarcoasterbook.com/wp-content/uploads/2026/06/Solar-Coaster-Intro-4.png" },
  { id: "3485-solarcoasterbook", slug: "the-solar-afterlife-what-happens-when-solar-farms-retire-ep-43", category: "Solar", title: "The Solar Afterlife: What Happens When Solar Farms Retire? – EP 43", img: "https://solarcoasterbook.com/wp-content/uploads/2026/06/Solar-Coaster-Intro-3.png" },
  { id: "3480-solarcoasterbook", slug: "made-in-america-the-solar-supply-chain-revolution-ep-42", category: "Solar", title: "Made in America: The Solar Supply Chain Revolution – EP 42", img: "https://solarcoasterbook.com/wp-content/uploads/2026/06/Solar-Coaster-Intro-2.png" },
  { id: "3475-solarcoasterbook", slug: "renewable-energys-new-reality-share-the-risk-or-miss-the-opportunity-ep-41", category: "Solar", title: "Renewable Energy’s New Reality: Share the Risk or Miss the Opportunity – EP 41", img: "https://solarcoasterbook.com/wp-content/uploads/2026/06/Solar-Coaster-Intro-1.png" },
  { id: "3470-solarcoasterbook", slug: "the-great-energy-divide-why-oil-volatility-is-accelerating-the-solar-revolution-ep-40", category: "Solar", title: "The Great Energy Divide: Why Oil Volatility Is Accelerating the Solar Revolution – EP 40", img: "https://solarcoasterbook.com/wp-content/uploads/2026/06/Solar-Coaster-Intro.png" },
  { id: "3457-solarcoasterbook", slug: "the-silent-saboteur-why-solar-is-really-a-30-year-bet-ep-39", category: "Solar", title: "The Silent Saboteur: Why Solar Is Really a 30-Year Bet – EP 39", img: "https://solarcoasterbook.com/wp-content/uploads/2026/05/Solar-Coaster-Intro-3.png" },
  { id: "3456-solarcoasterbook", slug: "the-solar-paradox-why-infrastructure-will-define-the-next-decade-ep-38", category: "Solar", title: "The Solar Paradox: Why Infrastructure Will Define the Next Decade – Ep 38", img: "https://solarcoasterbook.com/wp-content/uploads/2026/05/Solar-Coaster-Intro-2.png" },
  { id: "3455-solarcoasterbook", slug: "the-invisible-architects-behind-the-solar-revolution-ep-37", category: "Solar", title: "The Invisible Architects Behind the Solar Revolution – EP 37", img: "https://solarcoasterbook.com/wp-content/uploads/2026/05/Solar-Coaster-Intro-1.png" },
]

/* ---------- CASE STUDIES ---------- */
const CS_LOREM = 'We partnered end to end — strategy, brand, build, and growth — aligning every touchpoint around a single, measurable goal. From positioning and design system to a fast, SEO-ready site and an always-on acquisition engine, the work was built to convert and to scale.'

export const CASE_STUDIES = [
  {
    slug: 'wolf-river-construction',
    title: 'Wolf River Construction',
    tags: ['Branding', 'Web Development', 'WordPress', 'GoHighLevel', 'PostGrid'],
    excerpt: 'A Midwest roofing and exterior-renovation contractor rebranded and rebuilt on WordPress — with an interactive roofing calculator feeding an automated GoHighLevel and PostGrid follow-up engine.',
    cover: '/case-studies/wolf-river-construction/cover.png',
    description: 'Wolf River Construction is a Midwest roofing and exterior-renovation company that needed a digital presence as dependable as its craftsmanship. We built a bold, high-contrast brand and a conversion-focused WordPress site — anchored by an interactive roofing calculator and clear paths to a free quote — that positions Wolf River as a premium, GAF Master Elite contractor across residential, commercial, and solar work.\n\nBehind the scenes, we wired the site into GoHighLevel so every lead flows straight into an automated follow-up pipeline, and integrated PostGrid to trigger direct-mail outreach without manual effort. The result is a marketing engine that captures homeowners at the moment of intent and keeps Wolf River in front of them across both digital and print.',
    images: ['/case-studies/wolf-river-construction/1.png', '/case-studies/wolf-river-construction/2.png', '/case-studies/wolf-river-construction/3.png', '/case-studies/wolf-river-construction/4.png', '/case-studies/wolf-river-construction/5.png'],
  },
  {
    slug: 'northwind-saas',
    title: 'Northwind SaaS',
    tags: ['Web Design', 'SEO', 'Programmatic'],
    excerpt: 'A B2B SaaS marketing site rebuilt for speed and search — paired with an always-on programmatic engine.',
    cover: '/case-studies/northwind-saas/cover.svg',
    description: 'NORTHWIND is a B2B SaaS platform that needed a marketing site to match its ambition.\n\n' + CS_LOREM,
    images: ['/case-studies/northwind-saas/1.svg', '/case-studies/northwind-saas/2.svg', '/case-studies/northwind-saas/3.svg', '/case-studies/northwind-saas/4.svg'],
  },
  {
    slug: 'lumen-solar',
    title: 'Lumen Solar',
    tags: ['Brand Creation', 'Web Development', 'Paid Social'],
    excerpt: 'A solar installer relaunched with a clean identity, a lead-gen site, and a paid social program that fills the pipeline.',
    cover: '/case-studies/lumen-solar/cover.svg',
    description: 'LUMEN SOLAR came to us to stand out in a crowded, fast-moving market.\n\n' + CS_LOREM,
    images: ['/case-studies/lumen-solar/1.svg', '/case-studies/lumen-solar/2.svg', '/case-studies/lumen-solar/3.svg', '/case-studies/lumen-solar/4.svg'],
  },
  {
    slug: 'meridian-health',
    title: 'Meridian Health',
    tags: ['UX/UI', 'Technology Consulting', 'SEO'],
    excerpt: 'A healthcare platform redesigned around patient clarity, accessibility, and organic discoverability.',
    cover: '/case-studies/meridian-health/cover.svg',
    description: 'MERIDIAN HEALTH needed a digital experience patients could trust at a glance.\n\n' + CS_LOREM,
    images: ['/case-studies/meridian-health/1.svg', '/case-studies/meridian-health/2.svg', '/case-studies/meridian-health/3.svg', '/case-studies/meridian-health/4.svg'],
  },
  {
    slug: 'cobalt-fintech',
    title: 'Cobalt Fintech',
    tags: ['Brand Building', 'SEM', 'Analytics'],
    excerpt: 'A fintech challenger positioned for its Series B — full rebrand, performance search, and a measurement stack that proves ROI.',
    cover: '/case-studies/cobalt-fintech/cover.svg',
    description: 'COBALT is a fintech challenger that needed to look and perform like a category leader.\n\n' + CS_LOREM,
    images: ['/case-studies/cobalt-fintech/1.svg', '/case-studies/cobalt-fintech/2.svg', '/case-studies/cobalt-fintech/3.svg', '/case-studies/cobalt-fintech/4.svg'],
  },
  {
    slug: 'harbor-retail',
    title: 'Harbor Retail',
    tags: ['Traditional Full Service', 'Social Media', 'Web'],
    excerpt: 'An omnichannel retail brand unified across print, broadcast, social, and a conversion-focused storefront.',
    cover: '/case-studies/harbor-retail/cover.svg',
    description: 'HARBOR RETAIL wanted one coherent brand across every channel its customers touch.\n\n' + CS_LOREM,
    images: ['/case-studies/harbor-retail/1.svg', '/case-studies/harbor-retail/2.svg', '/case-studies/harbor-retail/3.svg', '/case-studies/harbor-retail/4.svg'],
  },
]
